// Material options organized by category for ComboBox usage.
// Label format: "Category – Material" so the dropdown is grouped and searchable.
// Value stored is the bare material name.
export const MATERIAL_OPTIONS = [
  // Steel
  { label: "Steel – 1018", value: "1018" },
  { label: "Steel – 1045", value: "1045" },
  { label: "Steel – 4140", value: "4140" },
  { label: "Steel – 4340", value: "4340" },
  { label: "Steel – 4330", value: "4330" },
  { label: "Steel – 8620", value: "8620" },
  { label: "Steel – O1 tool steel", value: "O1 tool steel" },
  { label: "Steel – A2 tool steel", value: "A2 tool steel" },
  { label: "Steel – D2 tool steel", value: "D2 tool steel" },
  { label: "Steel – H13 tool steel", value: "H13 tool steel" },
  { label: "Steel – M2 HSS", value: "M2 HSS" },
  // Stainless
  { label: "Stainless – 303", value: "303" },
  { label: "Stainless – 304 / 304L", value: "304 / 304L" },
  { label: "Stainless – 316 / 316L", value: "316 / 316L" },
  { label: "Stainless – 410", value: "410" },
  { label: "Stainless – 416", value: "416" },
  { label: "Stainless – 440C", value: "440C" },
  { label: "Stainless – 17-4 PH", value: "17-4 PH" },
  { label: "Stainless – 15-5 PH", value: "15-5 PH" },
  { label: "Stainless – 2205 Duplex", value: "2205 Duplex" },
  // Aluminum
  { label: "Aluminum – 2024", value: "2024" },
  { label: "Aluminum – 6061", value: "6061" },
  { label: "Aluminum – 6063", value: "6063" },
  { label: "Aluminum – 7050", value: "7050" },
  { label: "Aluminum – 7075", value: "7075" },
  { label: "Aluminum – MIC-6", value: "MIC-6" },
  // Titanium
  { label: "Titanium – Grade 1", value: "Grade 1" },
  { label: "Titanium – Grade 2", value: "Grade 2" },
  { label: "Titanium – Grade 4", value: "Grade 4" },
  { label: "Titanium – Grade 5 / 6Al-4V", value: "Grade 5 / 6Al-4V" },
  { label: "Titanium – 6Al-4V ELI", value: "6Al-4V ELI" },
  { label: "Titanium – 6-2-4-2", value: "6-2-4-2" },
  { label: "Titanium – 6-2-4-6", value: "6-2-4-6" },
  { label: "Titanium – 3Al-2.5V", value: "3Al-2.5V" },
  // Copper Alloys
  { label: "Copper Alloys – 110 Copper", value: "110 Copper" },
  { label: "Copper Alloys – 145 Tellurium Copper", value: "145 Tellurium Copper" },
  { label: "Copper Alloys – 360 Brass", value: "360 Brass" },
  { label: "Copper Alloys – 464 Naval Brass", value: "464 Naval Brass" },
  { label: "Copper Alloys – 544 Phosphor Bronze", value: "544 Phosphor Bronze" },
  { label: "Copper Alloys – 932 Bearing Bronze", value: "932 Bearing Bronze" },
  { label: "Copper Alloys – 954 Aluminum Bronze", value: "954 Aluminum Bronze" },
  // Nickel Alloys
  { label: "Nickel Alloys – Inconel 625", value: "Inconel 625" },
  { label: "Nickel Alloys – Inconel 718", value: "Inconel 718" },
  { label: "Nickel Alloys – Hastelloy C-276", value: "Hastelloy C-276" },
  { label: "Nickel Alloys – Monel 400", value: "Monel 400" },
  { label: "Nickel Alloys – Monel K-500", value: "Monel K-500" },
  { label: "Nickel Alloys – Waspaloy", value: "Waspaloy" },
  // Plastics
  { label: "Plastics – Delrin / Acetal", value: "Delrin / Acetal" },
  { label: "Plastics – PEEK", value: "PEEK" },
  { label: "Plastics – Nylon 6 / 6-6", value: "Nylon 6 / 6-6" },
  { label: "Plastics – UHMW-PE", value: "UHMW-PE" },
  { label: "Plastics – PTFE / Teflon", value: "PTFE / Teflon" },
  { label: "Plastics – Polycarbonate", value: "Polycarbonate" },
  { label: "Plastics – Acrylic / PMMA", value: "Acrylic / PMMA" },
  { label: "Plastics – PVC", value: "PVC" },
  { label: "Plastics – HDPE", value: "HDPE" },
  { label: "Plastics – Ultem / PEI", value: "Ultem / PEI" },
  { label: "Plastics – PVDF / Kynar", value: "PVDF / Kynar" },
  // Composites
  { label: "Composites – G-10 / FR4", value: "G-10 / FR4" },
  { label: "Composites – G-11", value: "G-11" },
  { label: "Composites – CE Phenolic", value: "CE Phenolic" },
  { label: "Composites – LE Phenolic", value: "LE Phenolic" },
  { label: "Composites – Carbon fiber", value: "Carbon fiber" },
  { label: "Composites – CFRP", value: "CFRP" },
  { label: "Composites – Micarta", value: "Micarta" },
  // Other Metals
  { label: "Other Metals – Magnesium AZ31", value: "Magnesium AZ31" },
  { label: "Other Metals – Magnesium AZ91", value: "Magnesium AZ91" },
  { label: "Other Metals – Zinc / Zamak", value: "Zinc / Zamak" },
  { label: "Other Metals – Lead", value: "Lead" },
  { label: "Other Metals – Tungsten", value: "Tungsten" },
  { label: "Other Metals – Cobalt alloy / Stellite", value: "Cobalt alloy / Stellite" },
];