// Material options organized by category for ComboBox usage.
// Label format: "Material, Category" so the dropdown is grouped and searchable.
// Value stored is the bare material name.
export const MATERIAL_OPTIONS = [
  // Steel
  { label: "1018, Steel", value: "1018" },
  { label: "1045, Steel", value: "1045" },
  { label: "4140, Steel", value: "4140" },
  { label: "4340, Steel", value: "4340" },
  { label: "4330, Steel", value: "4330" },
  { label: "8620, Steel", value: "8620" },
  { label: "O1 tool steel, Steel", value: "O1 tool steel" },
  { label: "A2 tool steel, Steel", value: "A2 tool steel" },
  { label: "D2 tool steel, Steel", value: "D2 tool steel" },
  { label: "H13 tool steel, Steel", value: "H13 tool steel" },
  { label: "M2 HSS, Steel", value: "M2 HSS" },
  // Stainless
  { label: "303, Stainless", value: "303" },
  { label: "304 / 304L, Stainless", value: "304 / 304L" },
  { label: "316 / 316L, Stainless", value: "316 / 316L" },
  { label: "410, Stainless", value: "410" },
  { label: "416, Stainless", value: "416" },
  { label: "440C, Stainless", value: "440C" },
  { label: "17-4 PH, Stainless", value: "17-4 PH" },
  { label: "15-5 PH, Stainless", value: "15-5 PH" },
  { label: "2205 Duplex, Stainless", value: "2205 Duplex" },
  // Aluminum
  { label: "2024, Aluminum", value: "2024" },
  { label: "6061, Aluminum", value: "6061" },
  { label: "6063, Aluminum", value: "6063" },
  { label: "7050, Aluminum", value: "7050" },
  { label: "7075, Aluminum", value: "7075" },
  { label: "MIC-6, Aluminum", value: "MIC-6" },
  // Titanium
  { label: "Grade 1, Titanium", value: "Grade 1" },
  { label: "Grade 2, Titanium", value: "Grade 2" },
  { label: "Grade 4, Titanium", value: "Grade 4" },
  { label: "Grade 5 / 6Al-4V, Titanium", value: "Grade 5 / 6Al-4V" },
  { label: "6Al-4V ELI, Titanium", value: "6Al-4V ELI" },
  { label: "6-2-4-2, Titanium", value: "6-2-4-2" },
  { label: "6-2-4-6, Titanium", value: "6-2-4-6" },
  { label: "3Al-2.5V, Titanium", value: "3Al-2.5V" },
  // Copper Alloys
  { label: "110 Copper, Copper Alloy", value: "110 Copper" },
  { label: "145 Tellurium Copper, Copper Alloy", value: "145 Tellurium Copper" },
  { label: "360 Brass, Copper Alloy", value: "360 Brass" },
  { label: "464 Naval Brass, Copper Alloy", value: "464 Naval Brass" },
  { label: "544 Phosphor Bronze, Copper Alloy", value: "544 Phosphor Bronze" },
  { label: "932 Bearing Bronze, Copper Alloy", value: "932 Bearing Bronze" },
  { label: "954 Aluminum Bronze, Copper Alloy", value: "954 Aluminum Bronze" },
  // Nickel Alloys
  { label: "Inconel 625, Nickel Alloy", value: "Inconel 625" },
  { label: "Inconel 718, Nickel Alloy", value: "Inconel 718" },
  { label: "Hastelloy C-276, Nickel Alloy", value: "Hastelloy C-276" },
  { label: "Monel 400, Nickel Alloy", value: "Monel 400" },
  { label: "Monel K-500, Nickel Alloy", value: "Monel K-500" },
  { label: "Waspaloy, Nickel Alloy", value: "Waspaloy" },
  // Plastics
  { label: "Delrin / Acetal, Plastic", value: "Delrin / Acetal" },
  { label: "PEEK, Plastic", value: "PEEK" },
  { label: "Nylon 6 / 6-6, Plastic", value: "Nylon 6 / 6-6" },
  { label: "UHMW-PE, Plastic", value: "UHMW-PE" },
  { label: "PTFE / Teflon, Plastic", value: "PTFE / Teflon" },
  { label: "Polycarbonate, Plastic", value: "Polycarbonate" },
  { label: "Acrylic / PMMA, Plastic", value: "Acrylic / PMMA" },
  { label: "PVC, Plastic", value: "PVC" },
  { label: "HDPE, Plastic", value: "HDPE" },
  { label: "Ultem / PEI, Plastic", value: "Ultem / PEI" },
  { label: "PVDF / Kynar, Plastic", value: "PVDF / Kynar" },
  // Composites
  { label: "G-10 / FR4, Composite", value: "G-10 / FR4" },
  { label: "G-11, Composite", value: "G-11" },
  { label: "CE Phenolic, Composite", value: "CE Phenolic" },
  { label: "LE Phenolic, Composite", value: "LE Phenolic" },
  { label: "Carbon fiber, Composite", value: "Carbon fiber" },
  { label: "CFRP, Composite", value: "CFRP" },
  { label: "Micarta, Composite", value: "Micarta" },
  // Other Metals (no category prefix)
  { label: "Magnesium AZ31", value: "Magnesium AZ31" },
  { label: "Magnesium AZ91", value: "Magnesium AZ91" },
  { label: "Zinc / Zamak", value: "Zinc / Zamak" },
  { label: "Lead", value: "Lead" },
  { label: "Tungsten", value: "Tungsten" },
  { label: "Cobalt alloy / Stellite", value: "Cobalt alloy / Stellite" },
];

export const MATERIAL_CONDITIONS = [
  "None",
  "Normalized (Norm.)",
  "Annealed (Ann.)",
  "Hardened (Hard.)",
  "Tempered (Temp.)",
  "Stress Relieved (S.R.)",
];