// Material options organized by category for ComboBox usage.
// Label format: "Material, Category" so the dropdown is grouped and searchable.
// Value stored is the bare material name.
export const MATERIAL_OPTIONS = [
  // Steel
  { label: "1018, Steel", value: "1018, Steel" },
  { label: "1045, Steel", value: "1045, Steel" },
  { label: "4140, Steel", value: "4140, Steel" },
  { label: "4340, Steel", value: "4340, Steel" },
  { label: "4330, Steel", value: "4330, Steel" },
  { label: "8620, Steel", value: "8620, Steel" },
  { label: "O1 tool steel, Steel", value: "O1 tool steel, Steel" },
  { label: "A2 tool steel, Steel", value: "A2 tool steel, Steel" },
  { label: "D2 tool steel, Steel", value: "D2 tool steel, Steel" },
  { label: "H13 tool steel, Steel", value: "H13 tool steel, Steel" },
  { label: "M2 HSS, Steel", value: "M2 HSS, Steel" },
  // Stainless
  { label: "303, Stainless", value: "303, Stainless" },
  { label: "304 / 304L, Stainless", value: "304 / 304L, Stainless" },
  { label: "316 / 316L, Stainless", value: "316 / 316L, Stainless" },
  { label: "410, Stainless", value: "410, Stainless" },
  { label: "416, Stainless", value: "416, Stainless" },
  { label: "440C, Stainless", value: "440C, Stainless" },
  { label: "17-4 PH, Stainless", value: "17-4 PH, Stainless" },
  { label: "15-5 PH, Stainless", value: "15-5 PH, Stainless" },
  { label: "2205 Duplex, Stainless", value: "2205 Duplex, Stainless" },
  // Aluminum
  { label: "2024, Aluminum", value: "2024, Aluminum" },
  { label: "6061, Aluminum", value: "6061, Aluminum" },
  { label: "6063, Aluminum", value: "6063, Aluminum" },
  { label: "7050, Aluminum", value: "7050, Aluminum" },
  { label: "7075, Aluminum", value: "7075, Aluminum" },
  { label: "MIC-6, Aluminum", value: "MIC-6, Aluminum" },
  // Titanium
  { label: "Grade 1, Titanium", value: "Grade 1, Titanium" },
  { label: "Grade 2, Titanium", value: "Grade 2, Titanium" },
  { label: "Grade 4, Titanium", value: "Grade 4, Titanium" },
  { label: "Grade 5 / 6Al-4V, Titanium", value: "Grade 5 / 6Al-4V, Titanium" },
  { label: "6Al-4V ELI, Titanium", value: "6Al-4V ELI, Titanium" },
  { label: "6-2-4-2, Titanium", value: "6-2-4-2, Titanium" },
  { label: "6-2-4-6, Titanium", value: "6-2-4-6, Titanium" },
  { label: "3Al-2.5V, Titanium", value: "3Al-2.5V, Titanium" },
  // Copper Alloys
  { label: "110 Copper, Copper Alloy", value: "110 Copper, Copper Alloy" },
  { label: "145 Tellurium Copper, Copper Alloy", value: "145 Tellurium Copper, Copper Alloy" },
  { label: "360 Brass, Copper Alloy", value: "360 Brass, Copper Alloy" },
  { label: "464 Naval Brass, Copper Alloy", value: "464 Naval Brass, Copper Alloy" },
  { label: "544 Phosphor Bronze, Copper Alloy", value: "544 Phosphor Bronze, Copper Alloy" },
  { label: "932 Bearing Bronze, Copper Alloy", value: "932 Bearing Bronze, Copper Alloy" },
  { label: "954 Aluminum Bronze, Copper Alloy", value: "954 Aluminum Bronze, Copper Alloy" },
  // Nickel Alloys
  { label: "Inconel 625, Nickel Alloy", value: "Inconel 625, Nickel Alloy" },
  { label: "Inconel 718, Nickel Alloy", value: "Inconel 718, Nickel Alloy" },
  { label: "Hastelloy C-276, Nickel Alloy", value: "Hastelloy C-276, Nickel Alloy" },
  { label: "Monel 400, Nickel Alloy", value: "Monel 400, Nickel Alloy" },
  { label: "Monel K-500, Nickel Alloy", value: "Monel K-500, Nickel Alloy" },
  { label: "Waspaloy, Nickel Alloy", value: "Waspaloy, Nickel Alloy" },
  // Plastics
  { label: "Delrin / Acetal, Plastic", value: "Delrin / Acetal, Plastic" },
  { label: "PEEK, Plastic", value: "PEEK, Plastic" },
  { label: "Nylon 6 / 6-6, Plastic", value: "Nylon 6 / 6-6, Plastic" },
  { label: "UHMW-PE, Plastic", value: "UHMW-PE, Plastic" },
  { label: "PTFE / Teflon, Plastic", value: "PTFE / Teflon, Plastic" },
  { label: "Polycarbonate, Plastic", value: "Polycarbonate, Plastic" },
  { label: "Acrylic / PMMA, Plastic", value: "Acrylic / PMMA, Plastic" },
  { label: "PVC, Plastic", value: "PVC, Plastic" },
  { label: "HDPE, Plastic", value: "HDPE, Plastic" },
  { label: "Ultem / PEI, Plastic", value: "Ultem / PEI, Plastic" },
  { label: "PVDF / Kynar, Plastic", value: "PVDF / Kynar, Plastic" },
  // Composites
  { label: "G-10 / FR4, Composite", value: "G-10 / FR4, Composite" },
  { label: "G-11, Composite", value: "G-11, Composite" },
  { label: "CE Phenolic, Composite", value: "CE Phenolic, Composite" },
  { label: "LE Phenolic, Composite", value: "LE Phenolic, Composite" },
  { label: "Carbon fiber, Composite", value: "Carbon fiber, Composite" },
  { label: "CFRP, Composite", value: "CFRP, Composite" },
  { label: "Micarta, Composite", value: "Micarta, Composite" },
  // Other Metals (no category prefix)
  { label: "Magnesium AZ31", value: "Magnesium AZ31" },
  { label: "Magnesium AZ91", value: "Magnesium AZ91" },
  { label: "Zinc / Zamak", value: "Zinc / Zamak" },
  { label: "Lead", value: "Lead" },
  { label: "Tungsten", value: "Tungsten" },
  { label: "Cobalt alloy / Stellite", value: "Cobalt alloy / Stellite" },
];

export const MATERIAL_CONDITIONS = [
  { label: "None", value: "None" },
  { label: "Normalized", value: "Norm." },
  { label: "Annealed", value: "Ann." },
  { label: "Hardened", value: "Hard." },
  { label: "Tempered", value: "Temp." },
  { label: "Stress Relieved", value: "S.R." },
];